<?php
$stockarray = array(
    'NASDAQ' => 'INDEXNASDAQ:NDX',
    'FTSE' => 'INDEXFTSE:UKX',
    'S&P' => 'INDEXSP:.INX',
    'DJI' => 'INDEXDJX:.DJI',
    'General Motors' => 'NYSE:GM',
    'Google' => 'NASDAQ:GOOG',
    'Apple' => 'NASDAQ:AAPL',
    'AIG' => 'NYSE:AIG',
    'Citigroup' => 'NYSE:C',
    'JP Morgan' => 'NYSE:JPM',
    'Microsoft' => 'NASDAQ:MSFT',
    'Facebook' => 'NASDAQ:FB',
    'Bank of America' => 'NYSE:BAC',
    'Visa' => 'NYSE:V',
    'General Electric' => 'NYSE:GE',
    'Pfizer' => 'NYSE:PFE',
    'Verizon' => 'NYSE:VZ',
    'Ford Motors' => 'NYSE:F',
    'Intel' => 'NASDAQ:INTC',
    'Nokia' => 'NYSE:NOK',
    'Exxon Mobil' => 'NYSE:XOM',
    'AT&T' => 'NYSE:T',
    'Proctor & Gamble' => 'NYSE:PG',
    'Cisco' => 'NASDAQ:CSCO',
    'Comcast' => 'NASDAQ:CMCSA',
    'Time Warner' => 'NYSE:TWX',
    'Twenty-First Century Fox' => 'NASDAQ:FOX',
    'CBS' => 'NYSE:CBS',
    'Viacom' => 'NASDAQ:VIAB',
    'Walt Disney' => 'NYSE:DIS'
);
?>